config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index] do
    resources :ideas
  end

  namespace :admin do
    resources :categories
    resources :images
    resources :ideas,  only: [:index, :show]
    resources :users, only: [:index, :show]
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "admin/base#dashboard"
  get "/", to: "base#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, uniqueness: true 
  has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  has_many :image_ideas
  has_many :images, through: :image_ideas
  belongs_to :category
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :name, :image
  has_many :image_ideas
  has_many :ideas, through: :image_ideas
end

app/models/image_idea.rb
class ImageIdea < ApplicationRecord
  belongs_to :idea
  belongs_to :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :password, presence: true
  validates :username, presence: true, uniqueness: true
  has_many :ideas

  enum role: [:default, :admin]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :user_admin?

  def dashboard
    @users = User.all
    @ideas = Idea.all
    @categories = Category.all
  end

private  
 def user_admin?
   render file: '/public/404' unless current_admin?
 end

end

app/controllers/admin/ideas_controller.rb
class Admin::IdeasController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = current_user
    @idea = Idea.find(params[:id])
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      # byebug
      redirect_to admin_image_path(@image)
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to admin_image_path(@image)
    else
      redirect_to request.referrer
    end
  end

  def destroy
    image = Image.find(params[:id])
    image.destroy
    redirect_to admin_images_path
  end

  private

  def image_params
    params.require(:image).permit(:image, :name, idea_ids: [])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 def index
   @users = User.all
 end

 def show
   @admin = current_user
   @user = User.find(params[:id])
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def current_user?
    render file: '/public/404' unless current_user
  end

  def user_admin?
    render file: '/public/404' unless current_admin?
  end

end

app/controllers/base_controller.rb
class BaseController < ApplicationController

  def current_user?
    render file: '/public/404' unless current_user
  end

  def index
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :current_user?, except: [:new, :create]
  before_action @user = :current_user

  def index
    @user
  end

  def show
    @idea = @user.ideas.find(params[:id])
    if @ideas.nil?
      redirect_to user_path(@user)
    end
  end

  def new
    @idea = Idea.new
    @categories = Category.all
    @images = Image.all
  end

  def create
    @idea = @user.ideas.new(idea_params)
    if @idea.save
      flash[:message] = "#{@idea.title} was created successfully!"
      redirect_to user_idea_path(@idea.user, @idea)
    else
      flash[:message] = "Unable to create idea. Something went wrong"
      redirect_to new_user_idea_path(current_user)
    end
  end

  def edit
    @categories = Category.all
    @images = Image.all
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.update(idea_params)
    if @idea.save
      flash[:message] = "#{@idea.title} successfully updated"
      redirect_to user_idea_path(@idea.user, @idea) if @user.role != "admin"
      redirect_to admin_idea_path(@idea) if @user.role == "admin"
    else
      flash[:message] = "#{@idea.title} was not updated. Maybe a field was left blank?"
      render :edit
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    image_idea = ImageIdea.where(idea_id: params[:id])
    image_idea.destroy_all
    if @idea.destroy
      flash[:message] = "#{@idea.title} was deleted"
      redirect_to user_ideas_path(@idea.user) if @user.role != "admin"
      redirect_to admin_ideas_path(@idea.user) if @user.role == "admin"
    else
      flash[:message] = "#{@idea.title} was not deleted. Please try again."
      redirect_to request.referrer
    end
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :content, :category_id, image_ids: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
    if @user.nil?
      redirect_to login_path
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user) if @user.role != "admin"
      redirect_to admin_user_path(@user) if @user.role == "admin"
    else
      render :edit
    end
  end

  def destroy
    user = User.find(session[:user_id])
    user.destroy
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/ideas_helper.rb
module Admin::IdeasHelper
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/ideas/index.html.erb
<h1>Welcome, <%= User.find(session[:user_id]).username %>. Here are all the ideas.</h1>
<% @users.each do |user| %>
  <h4>All <%= user.username %>'s ideas:</h4><br>
  <% user.ideas.each do |idea| %>
    <h2>idea title: <%= idea.title %></h2>
    <%= link_to "see this idea", admin_idea_path(idea) %><br>
  <br>
  <% end %>
<% end %>

app/views/admin/ideas/show.html.erb
<h1><%= @user.username %>'s idea viewer</h1>

<h4>User with the ideas: <%= link_to @idea.user.username, admin_user_path(@idea.user) %><br></h4>
<p>Idea title: <%= @idea.title %><br></p>
<p>Idea body:<br> <%= @idea.content %></p>
<% @idea.images.each do |image| %>
  <%= image_tag image.image %>
<% end %><br>
<p>Categories: </p><br>
<%= @idea.category.title %>

<div class="user-edit-container">
  <%= link_to "Edit Idea", edit_user_idea_path(@idea) %>
  <%= link_to "Delete Idea", user_idea_path(@idea), method: 'delete' %>
</div>

app/views/admin/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
  <%= user.username %>
  <%= link_to "#{user.username}'s ideas", user_ideas_path(user) %></li>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @admin.username %>'s user viewer</h1>
<h2><%= @user.username %></h2>
<% @user.ideas.each do |idea| %>
  <h3><%= link_to idea.title, admin_idea_path(idea) %></h3><br>
<% end %>
<%= link_to "Create Idea", new_user_idea_path(@user) %>
<div class="user-edit-container">
  <%= link_to "Edit User", edit_user_path(@user) %>
</div>

app/views/ideas/_form.html.erb
<%= form_for([@user, @idea]) do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :content %>
<%= f.text_area :content %>

<%= f.collection_select :category_id, @categories, :id, :title, prompt: true%>
<p>Check the box to add images:</p>
<div>
  <%= hidden_field_tag 'idea[image_ids][]', nil %>
  <% @images.each do |image| %>
  <div>
    <%= check_box_tag('idea[image_ids][]', image.id, @idea.image_ids.include?(image.id), id: "image-#{image.id}") %>
    <label for=<%= "image-#{image.id}" %>><%= image_tag image.image, width: 100 %></label>
  </div>
  <% end %>
</div>

<%= f.submit %>

<% end %>

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>
<%= render partial: "form" %>

app/views/ideas/index.html.erb
<h1><%= @user.username %>'s ideas</h1>
<% if @user.ideas.empty? %>
  <h2>You have no ideas!</h2>
<% else %>
  <% @user.ideas.each do |idea| %>
  <% unless idea.images.empty? %>
  <p><%= image_tag idea.images.first.image %><p>
  <% end %>
    <h3><%= idea.title %></h3>
    <h3><%= idea.content %></h3><br>
    <h2><%= link_to "edit idea", edit_user_idea_path(@user, idea) %></h2><br>
    <h2><%= link_to "delete idea", user_idea_path(@user, idea), method: 'delete' %></h2><br>
  <% end %>
<% end %>
<%= link_to "Create A New Idea", new_user_idea_path(@user) %>

app/views/ideas/new.html.erb
<h1>Create New Idea</h1>

<%= render partial: 'form' %>

app/views/ideas/show.html.erb
<h1>This Idea</h1>
<h4>Owner: <%= @idea.user.username %></h4>
<h4>Title: <%= @idea.title %></h4>
<p>content: <%= @idea.content %></p>
<% if @idea.images.empty? %>
<p>There are no images for this idea!</p>
<% else %>
<% @idea.images.each do |image| %>
<%= image_tag image.image %>
<% end %>
<% end %>
<p>Category:</p>
<p><%= @idea.category.title %></p>
<%= link_to "delete idea", user_idea_path(@idea), method: 'delete' %>
<%= link_to "edit idea", edit_user_idea_path(@idea) %>

app/views/users/_form.html.erb
<div>
<%= form_for(@user) do |f| %>

<h4><%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :email %><br>
<%= f.text_field :email %><br>

<%= f.label :username %><br>
<%= f.text_field :username %><br>

<%= f.label :password %><br>
<%= f.password_field :password %><br>

<%= f.label :password_confirmation %><br>
<%= f.password_field :password_confirmation %><br>

<%= f.submit "Create Account" %><br>
</h4>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render partial: "form" %>

app/views/users/index.html.erb
<h1>All Users Index.</h1>
<% @users.each do |user| %>
  <%= user.username %>
  <%= user.email %>
<%= link_to "delete user", user_path(user), method: 'delete' %>
<%= link_to "edit user", edit_user_path(user) %>
<% end %>

app/views/users/new.html.erb
<h1>Create An Account</h1>
<%= render partial: "form"%>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Page</h1>
<ul>
  <li>Username: <%= @user.username %></li>
  <li>Email: <%= mail_to @user.email %></li><br>
</ul>
  <div class="card">
    <p><%= @user.username %>'s ideas:</p>
    <% if @user.ideas.empty? %>
    <p><%= @user.username %> has no ideas!</p>
    <% else %>
    <% @user.ideas.each do |idea| %>
    <% if idea.images.empty? %>
    <p>there are no images for this idea</p>
    <% else %>
    <a><%= image_tag idea.images.first.image %></a>
    <% end %>
    <div>
      <p>Idea title:</p>
      <h2><span><%= link_to idea.title, admin_idea_path(idea) %></span></h2>
    </div><br><br>
    <div>
      <span><%= idea.title %></span>
      <p><%= idea.content %></p>
    </div>
    <% end %>
    <% end %>
  </div>
    <br>

  <%= link_to "Create A New Idea", new_user_idea_path(@user), class: "new-idea" %>

  <% if @user.id == session[:user_id] || @user.admin %>
  <div class="user-edit-container">
    <%= link_to "Edit User", edit_user_path(@user) %>
  </div>
  <% end %><br><br>